version: '2.4'

services:
  frontend:
    image: ghcr.io/nguyenanhduchl/mttq-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    depends_on:
      - backend
    restart: always
    mem_limit: 100m

  backend:
    image: ghcr.io/nguyenanhduchl/mttq-backend:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/database.sqlite:/app/database.sqlite
      - ./backend/uploads:/app/uploads
    restart: always
    mem_limit: 800m
    links:
      - clamav

  clamav:
    image: clamav/clamav:latest
    container_name: mttq-clamav
    environment:
      - CLAMAV_NO_FRESHCLAMD=false
    volumes:
      - clamav-db:/var/lib/clamav
    ports:
      - "3310:3310"
    restart: always
    mem_limit: 1500m

volumes:
  clamav-db:
