server {
    listen 80;
    server_name mttq.vpdtcampha.vn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name mttq.vpdtcampha.vn;

    ssl_certificate /etc/nginx/certs/STAR_vpdtcampha_vn_cert_inter_root.crt;
    ssl_certificate_key /etc/nginx/certs/STAR_vpdtcampha_vn_private_key.key;

    client_max_body_size 500M;

    location / {
        proxy_pass http://14.225.172.225:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
