name: Get Logs
on: workflow_dispatch
jobs:
  get-logs:
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VNPT_HOST }}
          username: ${{ secrets.VNPT_USER }}
          password: ${{ secrets.VNPT_PASS }}
          port: 22
          script: |
            echo "=== Checking Host Nginx config ==="
            cat /etc/nginx/conf.d/*.conf || true
            cat /etc/nginx/sites-enabled/* || true
            cat /etc/nginx/nginx.conf || true
